name: Java CI

on: [push, pull_request, workflow_dispatch]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          java-version: 17
          distribution: temurin
      - name: Build desktop launcher
        run: |
          chmod +x gradlew
          ./gradlew desktop:dist --no-daemon --info --stacktrace
      - name: Upload built desktop launcher JAR file
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Arc-Template.jar (zipped)
          path: desktop/build/libs/Arc-Template.jar
